// ─── FlexMatches Demo Seed Data ───────────────────────────────────────────────
// 50 fictional users around Willow Grove, PA 19090
// For demo/testing only. Not real people.

export type DemoUser = {
  // ── DB fields (inserted into users table) ──
  id: string;
  email: string; // used for auth creation only
  username: string;
  full_name: string;
  bio: string;
  sports: string[];
  fitness_level: "beginner" | "intermediate" | "advanced";
  age: number;
  gender: "male" | "female" | "other";
  city: string;
  gym_name: string;
  lat: number;
  lng: number;
  preferred_times: string[]; // "morning" | "afternoon" | "evening"
  availability: string[];    // day names
  looking_for: string[];
  occupation: string;
  current_streak: number;
  avatar_url: null;          // always null — deterministic fallback handles it
  onboarding_completed: true;
  last_active: string;       // ISO string, recent
  // ── Demo-only fields (not stored in DB, used by chat engine) ──
  personality: "direct" | "friendly" | "reserved" | "hype";
  response_speed: "fast" | "medium" | "slow";
  main_goal: string;
  chat_notes: string;
};

// ─── Coord helpers (within ~10 miles of Willow Grove) ─────────────────────────
// Willow Grove center: 40.1434, -75.1224

function ago(days: number): string {
  return new Date(Date.now() - days * 86400000).toISOString();
}

export const DEMO_USERS: DemoUser[] = [
  // ─── MALES 1–20 ────────────────────────────────────────────────────────────

  {
    id: "demo0001-0000-0000-0000-000000000001",
    email: "demo.marcus@flexmatches-demo.local",
    username: "marcus_wg",
    full_name: "Marcus Thompson",
    bio: "Software engineer by day, gym rat by night. Looking for someone to push through those last few reps.",
    sports: ["Gym", "Running"],
    fitness_level: "intermediate",
    age: 28,
    gender: "male",
    city: "Willow Grove",
    gym_name: "LA Fitness - Willow Grove",
    lat: 40.1434, lng: -75.1224,
    preferred_times: ["evening"],
    availability: ["Monday", "Wednesday", "Friday"],
    looking_for: ["accountability", "gym buddy"],
    occupation: "Software Engineer",
    current_streak: 7,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "direct",
    response_speed: "fast",
    main_goal: "Build consistency and get stronger",
    chat_notes: "Gets to the point quickly. Asks about schedule first.",
  },
  {
    id: "demo0002-0000-0000-0000-000000000002",
    email: "demo.tyler@flexmatches-demo.local",
    username: "tyler_hoops",
    full_name: "Tyler Bennett",
    bio: "Weekend baller, weekday gym grind. New to lifting but serious about it. Let's work.",
    sports: ["Basketball", "Gym"],
    fitness_level: "beginner",
    age: 24,
    gender: "male",
    city: "Horsham",
    gym_name: "Anytime Fitness - Horsham",
    lat: 40.1776, lng: -75.1479,
    preferred_times: ["evening"],
    availability: ["Tuesday", "Thursday", "Saturday"],
    looking_for: ["gym buddy", "sports partner"],
    occupation: "Sales Associate",
    current_streak: 3,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "friendly",
    response_speed: "medium",
    main_goal: "Get in shape, play better ball",
    chat_notes: "Warm and easy to talk to. Mentions basketball often.",
  },
  {
    id: "demo0003-0000-0000-0000-000000000003",
    email: "demo.jaylen@flexmatches-demo.local",
    username: "jay_hoops31",
    full_name: "Jaylen Carter",
    bio: "Ball is life but the gym keeps me on the court. 5 days a week, no excuses 🔥",
    sports: ["Basketball", "Running", "Gym"],
    fitness_level: "intermediate",
    age: 31,
    gender: "male",
    city: "Abington",
    gym_name: "Planet Fitness - Willow Grove",
    lat: 40.1168, lng: -75.1168,
    preferred_times: ["morning", "evening"],
    availability: ["Monday", "Tuesday", "Thursday", "Saturday"],
    looking_for: ["sports partner", "accountability"],
    occupation: "Graphic Designer",
    current_streak: 12,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "hype",
    response_speed: "fast",
    main_goal: "Increase speed and vertical",
    chat_notes: "High energy. Fires back quickly. Lots of emojis.",
  },
  {
    id: "demo0004-0000-0000-0000-000000000004",
    email: "demo.derek@flexmatches-demo.local",
    username: "derek_lifts",
    full_name: "Derek Nolan",
    bio: "5 years of lifting. No nonsense, just results. Looking for someone who actually shows up.",
    sports: ["Gym", "CrossFit"],
    fitness_level: "advanced",
    age: 34,
    gender: "male",
    city: "Warminster",
    gym_name: "LA Fitness - Warminster",
    lat: 40.1979, lng: -75.0888,
    preferred_times: ["morning"],
    availability: ["Monday", "Wednesday", "Friday", "Saturday"],
    looking_for: ["gym buddy", "accountability"],
    occupation: "Physical Therapist",
    current_streak: 15,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "direct",
    response_speed: "medium",
    main_goal: "Maintain strength, help others improve",
    chat_notes: "No small talk. Straight to logistics.",
  },
  {
    id: "demo0005-0000-0000-0000-000000000005",
    email: "demo.chris@flexmatches-demo.local",
    username: "chris_flex",
    full_name: "Chris Morales",
    bio: "Gym 3x a week, yoga helps me recover. Open to training with anyone positive and consistent.",
    sports: ["Gym", "Yoga"],
    fitness_level: "intermediate",
    age: 26,
    gender: "male",
    city: "Jenkintown",
    gym_name: "Jenkintown YMCA",
    lat: 40.0951, lng: -75.1324,
    preferred_times: ["evening"],
    availability: ["Monday", "Wednesday", "Friday"],
    looking_for: ["gym buddy", "wellness partner"],
    occupation: "Marketing Coordinator",
    current_streak: 5,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "friendly",
    response_speed: "fast",
    main_goal: "Build muscle, reduce stress",
    chat_notes: "Warm and easy-going. Asks about your routine before suggesting anything.",
  },
  {
    id: "demo0006-0000-0000-0000-000000000006",
    email: "demo.brandon@flexmatches-demo.local",
    username: "brandon_trails",
    full_name: "Brandon Walsh",
    bio: "Hiker and weekend runner. Just moved to Glenside. Looking for trail buddies.",
    sports: ["Hiking", "Running"],
    fitness_level: "beginner",
    age: 29,
    gender: "male",
    city: "Glenside",
    gym_name: "Ambler Fitness Center",
    lat: 40.1026, lng: -75.1524,
    preferred_times: ["morning"],
    availability: ["Saturday", "Sunday"],
    looking_for: ["outdoor partner", "running buddy"],
    occupation: "Teacher",
    current_streak: 2,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(2),
    personality: "reserved",
    response_speed: "slow",
    main_goal: "Get outside more, build endurance",
    chat_notes: "Short replies. Prefers weekends. Shy at first.",
  },
  {
    id: "demo0007-0000-0000-0000-000000000007",
    email: "demo.anthony@flexmatches-demo.local",
    username: "tony_box",
    full_name: "Anthony Rivera",
    bio: "Boxing 4x a week plus gym work. If you train hard, we'll get along just fine 💪🔥",
    sports: ["Boxing", "Gym"],
    fitness_level: "intermediate",
    age: 33,
    gender: "male",
    city: "Willow Grove",
    gym_name: "LA Fitness - Willow Grove",
    lat: 40.1511, lng: -75.1198,
    preferred_times: ["evening"],
    availability: ["Tuesday", "Thursday", "Saturday"],
    looking_for: ["training partner", "accountability"],
    occupation: "Electrician",
    current_streak: 9,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "hype",
    response_speed: "medium",
    main_goal: "Stay lean, improve cardio and hand speed",
    chat_notes: "Intense but supportive. Asks if you do any combat sports.",
  },
  {
    id: "demo0008-0000-0000-0000-000000000008",
    email: "demo.kevin@flexmatches-demo.local",
    username: "kev_bball",
    full_name: "Kevin Osei",
    bio: "College freshman, been playing ball my whole life. Trying to get in the gym more consistently.",
    sports: ["Basketball", "Gym"],
    fitness_level: "beginner",
    age: 22,
    gender: "male",
    city: "Hatboro",
    gym_name: "Genesis Fitness - Hatboro",
    lat: 40.1737, lng: -75.1010,
    preferred_times: ["afternoon"],
    availability: ["Monday", "Wednesday", "Saturday", "Sunday"],
    looking_for: ["gym buddy", "sports partner"],
    occupation: "Student",
    current_streak: 1,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "friendly",
    response_speed: "fast",
    main_goal: "Get stronger, improve athleticism",
    chat_notes: "Enthusiastic but needs guidance. Asks lots of questions.",
  },
  {
    id: "demo0009-0000-0000-0000-000000000009",
    email: "demo.daniel@flexmatches-demo.local",
    username: "dan_cyclist",
    full_name: "Daniel Park",
    bio: "Distance runner and avid cyclist. I've run 4 half-marathons. Looking for someone to push my pace.",
    sports: ["Running", "Cycling"],
    fitness_level: "advanced",
    age: 38,
    gender: "male",
    city: "Ambler",
    gym_name: "Ambler Fitness Center",
    lat: 40.1537, lng: -75.2246,
    preferred_times: ["morning"],
    availability: ["Tuesday", "Thursday", "Sunday"],
    looking_for: ["running partner", "training partner"],
    occupation: "Accountant",
    current_streak: 11,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "direct",
    response_speed: "slow",
    main_goal: "Sub-2 hour half marathon",
    chat_notes: "Precise and data-oriented. Talks about splits and pace.",
  },
  {
    id: "demo0010-0000-0000-0000-000000000010",
    email: "demo.michael@flexmatches-demo.local",
    username: "mike_fw",
    full_name: "Michael Chen",
    bio: "Work hard, train harder. I hit the gym 4 evenings a week. Could use a spotter and some good company.",
    sports: ["Gym", "Running"],
    fitness_level: "intermediate",
    age: 27,
    gender: "male",
    city: "Fort Washington",
    gym_name: "24 Hour Fitness - Fort Washington",
    lat: 40.1426, lng: -75.2043,
    preferred_times: ["evening"],
    availability: ["Monday", "Tuesday", "Thursday", "Friday"],
    looking_for: ["gym buddy", "spotter"],
    occupation: "Financial Analyst",
    current_streak: 6,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "friendly",
    response_speed: "medium",
    main_goal: "Bulk up, improve overall fitness",
    chat_notes: "Professional tone. Asks about your gym schedule upfront.",
  },
  {
    id: "demo0011-0000-0000-0000-000000000011",
    email: "demo.james@flexmatches-demo.local",
    username: "james_nw",
    full_name: "James Whitfield",
    bio: "Yoga practitioner for 6 years, hiker on weekends. Looking to share some trail miles.",
    sports: ["Yoga", "Hiking"],
    fitness_level: "intermediate",
    age: 35,
    gender: "male",
    city: "North Wales",
    gym_name: "Planet Fitness - Warminster",
    lat: 40.2115, lng: -75.2774,
    preferred_times: ["morning"],
    availability: ["Saturday", "Sunday"],
    looking_for: ["outdoor partner", "wellness partner"],
    occupation: "Architect",
    current_streak: 4,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(2),
    personality: "reserved",
    response_speed: "slow",
    main_goal: "Mind-body balance, stay injury-free",
    chat_notes: "Measured and thoughtful. Prefers longer conversations over fast replies.",
  },
  {
    id: "demo0012-0000-0000-0000-000000000012",
    email: "demo.ryan@flexmatches-demo.local",
    username: "ryan_wg12",
    full_name: "Ryan Sullivan",
    bio: "Just got serious about training after too many years of excuses. Looking for a workout buddy to stay accountable.",
    sports: ["Gym", "Basketball"],
    fitness_level: "beginner",
    age: 25,
    gender: "male",
    city: "Willow Grove",
    gym_name: "Planet Fitness - Willow Grove",
    lat: 40.1399, lng: -75.1267,
    preferred_times: ["evening"],
    availability: ["Tuesday", "Thursday", "Saturday"],
    looking_for: ["accountability", "gym buddy"],
    occupation: "Nurse",
    current_streak: 2,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "friendly",
    response_speed: "medium",
    main_goal: "Build a consistent routine",
    chat_notes: "Honest about being a beginner. Appreciates encouragement.",
  },
  {
    id: "demo0013-0000-0000-0000-000000000013",
    email: "demo.alex@flexmatches-demo.local",
    username: "alex_cf",
    full_name: "Alex Kowalski",
    bio: "CrossFit 5 days a week. I love a challenge and hate excuses. Let's compete and push each other.",
    sports: ["CrossFit", "Gym"],
    fitness_level: "advanced",
    age: 30,
    gender: "male",
    city: "Horsham",
    gym_name: "CrossFit Horsham",
    lat: 40.1802, lng: -75.1502,
    preferred_times: ["morning"],
    availability: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    looking_for: ["training partner", "competition"],
    occupation: "Personal Trainer",
    current_streak: 20,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "direct",
    response_speed: "fast",
    main_goal: "Compete at local CrossFit events",
    chat_notes: "Competitive. Will ask about your WOD times immediately.",
  },
  {
    id: "demo0014-0000-0000-0000-000000000014",
    email: "demo.jordan@flexmatches-demo.local",
    username: "jordan_run",
    full_name: "Jordan Miles",
    bio: "3x half-marathon finisher and trail hiking enthusiast. Looking for a consistent running partner.",
    sports: ["Running", "Hiking"],
    fitness_level: "intermediate",
    age: 32,
    gender: "male",
    city: "Warminster",
    gym_name: "Planet Fitness - Warminster",
    lat: 40.1956, lng: -75.0912,
    preferred_times: ["morning"],
    availability: ["Wednesday", "Saturday", "Sunday"],
    looking_for: ["running partner", "outdoor partner"],
    occupation: "HR Manager",
    current_streak: 8,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "friendly",
    response_speed: "medium",
    main_goal: "Run a full marathon next year",
    chat_notes: "Conversational about routes and distances. Supportive energy.",
  },
  {
    id: "demo0015-0000-0000-0000-000000000015",
    email: "demo.eric@flexmatches-demo.local",
    username: "eric_ab",
    full_name: "Eric Johnson",
    bio: "Powerlifter-turned-cyclist. Big compound lifts in the morning, long rides on weekends.",
    sports: ["Gym", "Cycling"],
    fitness_level: "intermediate",
    age: 28,
    gender: "male",
    city: "Abington",
    gym_name: "Anytime Fitness - Horsham",
    lat: 40.1143, lng: -75.1188,
    preferred_times: ["morning"],
    availability: ["Monday", "Wednesday", "Saturday"],
    looking_for: ["gym buddy", "cycling partner"],
    occupation: "Contractor",
    current_streak: 5,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "direct",
    response_speed: "fast",
    main_goal: "Maintain strength while improving cardio",
    chat_notes: "Minimal words. Sets logistics quickly.",
  },
  {
    id: "demo0016-0000-0000-0000-000000000016",
    email: "demo.sean@flexmatches-demo.local",
    username: "sean_swim",
    full_name: "Sean Murphy",
    bio: "Masters swimmer and weekend cyclist. Prefer low-impact training but train hard within it.",
    sports: ["Swimming", "Cycling"],
    fitness_level: "advanced",
    age: 36,
    gender: "male",
    city: "Glenside",
    gym_name: "Jenkintown YMCA",
    lat: 40.1003, lng: -75.1498,
    preferred_times: ["morning"],
    availability: ["Tuesday", "Thursday", "Saturday"],
    looking_for: ["training partner", "swim buddy"],
    occupation: "Lawyer",
    current_streak: 10,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(2),
    personality: "reserved",
    response_speed: "slow",
    main_goal: "Improve swim splits, reduce injury risk",
    chat_notes: "Formal tone. Brief. Usually asks about your experience level first.",
  },
  {
    id: "demo0017-0000-0000-0000-000000000017",
    email: "demo.nathan@flexmatches-demo.local",
    username: "nate_energy",
    full_name: "Nathan Diaz",
    bio: "College athlete staying in shape post-grad. Gym 4x a week and I take it seriously 🏋️",
    sports: ["Gym", "Basketball"],
    fitness_level: "beginner",
    age: 23,
    gender: "male",
    city: "Jenkintown",
    gym_name: "Jenkintown YMCA",
    lat: 40.0968, lng: -75.1301,
    preferred_times: ["afternoon", "evening"],
    availability: ["Monday", "Wednesday", "Friday", "Saturday"],
    looking_for: ["gym buddy", "sports partner"],
    occupation: "Student",
    current_streak: 4,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "hype",
    response_speed: "fast",
    main_goal: "Stay athletic, don't let the college gains disappear",
    chat_notes: "Very energetic. Wants to know if you're competitive.",
  },
  {
    id: "demo0018-0000-0000-0000-000000000018",
    email: "demo.carlos@flexmatches-demo.local",
    username: "carlos_wg",
    full_name: "Carlos Reyes",
    bio: "Combat sports and strength training. 10 years in the gym, 3 in boxing. Serious training only.",
    sports: ["Boxing", "CrossFit"],
    fitness_level: "intermediate",
    age: 31,
    gender: "male",
    city: "Willow Grove",
    gym_name: "LA Fitness - Willow Grove",
    lat: 40.1468, lng: -75.1189,
    preferred_times: ["evening"],
    availability: ["Tuesday", "Thursday", "Friday"],
    looking_for: ["training partner", "accountability"],
    occupation: "Mechanic",
    current_streak: 6,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "direct",
    response_speed: "medium",
    main_goal: "Get fight-ready, stay conditioned",
    chat_notes: "Straight to the point about training style and intensity.",
  },
  {
    id: "demo0019-0000-0000-0000-000000000019",
    email: "demo.david@flexmatches-demo.local",
    username: "dave_trail",
    full_name: "David Harrington",
    bio: "Ultramarathon runner. Been training solo for too long. Would love a steady Saturday morning partner.",
    sports: ["Running", "Hiking"],
    fitness_level: "advanced",
    age: 40,
    gender: "male",
    city: "Hatboro",
    gym_name: "Genesis Fitness - Hatboro",
    lat: 40.1710, lng: -75.1038,
    preferred_times: ["morning"],
    availability: ["Saturday", "Sunday"],
    looking_for: ["running partner", "outdoor partner"],
    occupation: "Project Manager",
    current_streak: 14,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(3),
    personality: "reserved",
    response_speed: "slow",
    main_goal: "50K trail race in spring",
    chat_notes: "Thoughtful replies. Talks about specific trails and distances.",
  },
  {
    id: "demo0020-0000-0000-0000-000000000020",
    email: "demo.isaiah@flexmatches-demo.local",
    username: "zay_bball",
    full_name: "Isaiah Brooks",
    bio: "Full court, full effort. I ball hard on weekends and work on athleticism at the gym during the week 🔥",
    sports: ["Basketball", "Gym"],
    fitness_level: "intermediate",
    age: 27,
    gender: "male",
    city: "Ambler",
    gym_name: "Ambler Fitness Center",
    lat: 40.1514, lng: -75.2267,
    preferred_times: ["evening"],
    availability: ["Monday", "Thursday", "Saturday", "Sunday"],
    looking_for: ["sports partner", "gym buddy"],
    occupation: "Social Worker",
    current_streak: 5,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "hype",
    response_speed: "fast",
    main_goal: "Increase vert, stay on the court",
    chat_notes: "Talks about basketball a lot. Excited energy.",
  },

  // ─── FEMALES 1–20 (21–40) ──────────────────────────────────────────────────

  {
    id: "demo0021-0000-0000-0000-000000000021",
    email: "demo.ashley@flexmatches-demo.local",
    username: "ashley_fit",
    full_name: "Ashley Monroe",
    bio: "Gym 4x a week, yoga on Sundays. Looking for a consistent workout partner I can actually rely on.",
    sports: ["Gym", "Yoga"],
    fitness_level: "intermediate",
    age: 26,
    gender: "female",
    city: "Willow Grove",
    gym_name: "LA Fitness - Willow Grove",
    lat: 40.1421, lng: -75.1238,
    preferred_times: ["evening"],
    availability: ["Monday", "Wednesday", "Friday", "Sunday"],
    looking_for: ["gym buddy", "accountability"],
    occupation: "Nurse Practitioner",
    current_streak: 8,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "friendly",
    response_speed: "fast",
    main_goal: "Build strength and stay consistent",
    chat_notes: "Warm and organized. Likes to confirm plans clearly.",
  },
  {
    id: "demo0022-0000-0000-0000-000000000022",
    email: "demo.jasmine@flexmatches-demo.local",
    username: "jas_run",
    full_name: "Jasmine Okafor",
    bio: "Running and yoga keep me sane. Training for a 10K this spring. Partner motivation is everything.",
    sports: ["Running", "Yoga"],
    fitness_level: "intermediate",
    age: 30,
    gender: "female",
    city: "Horsham",
    gym_name: "Anytime Fitness - Horsham",
    lat: 40.1784, lng: -75.1456,
    preferred_times: ["morning"],
    availability: ["Wednesday", "Friday", "Saturday"],
    looking_for: ["running partner", "accountability"],
    occupation: "Speech Therapist",
    current_streak: 6,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "friendly",
    response_speed: "medium",
    main_goal: "Sub-60 minute 10K",
    chat_notes: "Mentions her 10K goal early. Likes to talk routes.",
  },
  {
    id: "demo0023-0000-0000-0000-000000000023",
    email: "demo.mia@flexmatches-demo.local",
    username: "mia_yoga",
    full_name: "Mia Delgado",
    bio: "Yoga twice a week, gym on off days. Still learning but showing up. Looking for a non-judgmental gym partner.",
    sports: ["Yoga", "Gym"],
    fitness_level: "beginner",
    age: 24,
    gender: "female",
    city: "Abington",
    gym_name: "Planet Fitness - Willow Grove",
    lat: 40.1183, lng: -75.1145,
    preferred_times: ["evening"],
    availability: ["Monday", "Thursday"],
    looking_for: ["gym buddy", "wellness partner"],
    occupation: "Barista",
    current_streak: 1,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(2),
    personality: "reserved",
    response_speed: "medium",
    main_goal: "Build a routine, feel better",
    chat_notes: "A bit shy. Short replies. Opens up once comfortable.",
  },
  {
    id: "demo0024-0000-0000-0000-000000000024",
    email: "demo.sofia@flexmatches-demo.local",
    username: "sofia_cf",
    full_name: "Sofia Vargas",
    bio: "CrossFit coach and competitive athlete. I train hard and I expect the same from partners 🏋️‍♀️",
    sports: ["CrossFit", "Gym"],
    fitness_level: "advanced",
    age: 33,
    gender: "female",
    city: "Jenkintown",
    gym_name: "CrossFit Horsham",
    lat: 40.0964, lng: -75.1309,
    preferred_times: ["morning"],
    availability: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    looking_for: ["training partner", "competition"],
    occupation: "CrossFit Coach",
    current_streak: 18,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "direct",
    response_speed: "fast",
    main_goal: "Regional qualifier this season",
    chat_notes: "Very clear about expectations. Asks about your benchmark times.",
  },
  {
    id: "demo0025-0000-0000-0000-000000000025",
    email: "demo.aisha@flexmatches-demo.local",
    username: "aisha_glenside",
    full_name: "Aisha Williams",
    bio: "Yoga practitioner and weekend hiker. Just looking for good company on trails and in the studio.",
    sports: ["Yoga", "Hiking"],
    fitness_level: "intermediate",
    age: 28,
    gender: "female",
    city: "Glenside",
    gym_name: "Jenkintown YMCA",
    lat: 40.1012, lng: -75.1539,
    preferred_times: ["morning"],
    availability: ["Saturday", "Sunday"],
    looking_for: ["outdoor partner", "wellness partner"],
    occupation: "UX Designer",
    current_streak: 5,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(3),
    personality: "friendly",
    response_speed: "slow",
    main_goal: "Decompress, stay active",
    chat_notes: "Laid-back. Prefers outdoor activity. Takes time to respond but warm.",
  },
  {
    id: "demo0026-0000-0000-0000-000000000026",
    email: "demo.rachel@flexmatches-demo.local",
    username: "rachel_pace",
    full_name: "Rachel Kim",
    bio: "Cyclist and runner, 4 days a week. Looking for someone to share early morning miles.",
    sports: ["Running", "Cycling"],
    fitness_level: "intermediate",
    age: 31,
    gender: "female",
    city: "Warminster",
    gym_name: "Planet Fitness - Warminster",
    lat: 40.1967, lng: -75.0901,
    preferred_times: ["morning"],
    availability: ["Tuesday", "Thursday", "Saturday"],
    looking_for: ["running partner", "training partner"],
    occupation: "Pharmacist",
    current_streak: 9,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "direct",
    response_speed: "medium",
    main_goal: "Triathlon finish this summer",
    chat_notes: "Goal-oriented. Asks about your pace and distance upfront.",
  },
  {
    id: "demo0027-0000-0000-0000-000000000027",
    email: "demo.morgan@flexmatches-demo.local",
    username: "morgan_ambler",
    full_name: "Morgan Davis",
    bio: "New to the gym but fully committed. Need someone experienced to show me the ropes and keep me honest.",
    sports: ["Gym", "Yoga"],
    fitness_level: "beginner",
    age: 25,
    gender: "female",
    city: "Ambler",
    gym_name: "Ambler Fitness Center",
    lat: 40.1521, lng: -75.2231,
    preferred_times: ["evening"],
    availability: ["Monday", "Wednesday", "Friday"],
    looking_for: ["gym buddy", "accountability"],
    occupation: "Social Media Manager",
    current_streak: 3,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "friendly",
    response_speed: "fast",
    main_goal: "Build confidence in the gym",
    chat_notes: "Asks lots of questions. Very appreciative of guidance.",
  },
  {
    id: "demo0028-0000-0000-0000-000000000028",
    email: "demo.priya@flexmatches-demo.local",
    username: "priya_fw",
    full_name: "Priya Sharma",
    bio: "Yoga instructor and occasional swimmer. Calm energy, consistent schedule. Looking for the same.",
    sports: ["Yoga", "Swimming"],
    fitness_level: "advanced",
    age: 34,
    gender: "female",
    city: "Fort Washington",
    gym_name: "Jenkintown YMCA",
    lat: 40.1434, lng: -75.2061,
    preferred_times: ["morning"],
    availability: ["Tuesday", "Thursday"],
    looking_for: ["wellness partner", "swim buddy"],
    occupation: "Yoga Instructor",
    current_streak: 12,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(4),
    personality: "reserved",
    response_speed: "slow",
    main_goal: "Deepen practice, support others",
    chat_notes: "Measured and calming. Takes her time with replies.",
  },
  {
    id: "demo0029-0000-0000-0000-000000000029",
    email: "demo.taylor@flexmatches-demo.local",
    username: "tay_nw",
    full_name: "Taylor Hughes",
    bio: "Gym girl who doesn't take rest days seriously 😅 Looking for a partner who'll actually drag me to the gym.",
    sports: ["Gym", "Running"],
    fitness_level: "intermediate",
    age: 27,
    gender: "female",
    city: "North Wales",
    gym_name: "Gold's Gym - North Wales",
    lat: 40.2128, lng: -75.2798,
    preferred_times: ["evening"],
    availability: ["Monday", "Wednesday", "Saturday"],
    looking_for: ["accountability", "gym buddy"],
    occupation: "Marketing Manager",
    current_streak: 4,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "hype",
    response_speed: "medium",
    main_goal: "Actually stick to a program",
    chat_notes: "Self-deprecating humor. Responds with energy once engaged.",
  },
  {
    id: "demo0030-0000-0000-0000-000000000030",
    email: "demo.nicole@flexmatches-demo.local",
    username: "nic_hatboro",
    full_name: "Nicole Foster",
    bio: "Gym and casual basketball. Was a D3 athlete. Looking for someone competitive and consistent.",
    sports: ["Gym", "Basketball"],
    fitness_level: "intermediate",
    age: 29,
    gender: "female",
    city: "Hatboro",
    gym_name: "Genesis Fitness - Hatboro",
    lat: 40.1718, lng: -75.1024,
    preferred_times: ["morning"],
    availability: ["Tuesday", "Thursday", "Saturday"],
    looking_for: ["gym buddy", "sports partner"],
    occupation: "Physical Education Teacher",
    current_streak: 7,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "direct",
    response_speed: "fast",
    main_goal: "Stay competitive post-college",
    chat_notes: "Athletic background comes through. Asks about training history.",
  },
  {
    id: "demo0031-0000-0000-0000-000000000031",
    email: "demo.elena@flexmatches-demo.local",
    username: "elena_wg",
    full_name: "Elena Russo",
    bio: "Just starting yoga and trying hiking for the first time this year. Would love someone patient and positive.",
    sports: ["Yoga", "Hiking"],
    fitness_level: "beginner",
    age: 22,
    gender: "female",
    city: "Willow Grove",
    gym_name: "Planet Fitness - Willow Grove",
    lat: 40.1448, lng: -75.1211,
    preferred_times: ["afternoon"],
    availability: ["Saturday", "Sunday"],
    looking_for: ["wellness partner", "outdoor partner"],
    occupation: "Student",
    current_streak: 1,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(2),
    personality: "friendly",
    response_speed: "medium",
    main_goal: "Feel healthier, enjoy the outdoors",
    chat_notes: "Genuine and honest about being new. Asks for advice.",
  },
  {
    id: "demo0032-0000-0000-0000-000000000032",
    email: "demo.brianna@flexmatches-demo.local",
    username: "bri_strong",
    full_name: "Brianna Scott",
    bio: "CrossFit and boxing. I'm competitive and I train with purpose. Looking for someone who matches that energy 💪🔥",
    sports: ["CrossFit", "Boxing"],
    fitness_level: "advanced",
    age: 35,
    gender: "female",
    city: "Horsham",
    gym_name: "CrossFit Horsham",
    lat: 40.1789, lng: -75.1465,
    preferred_times: ["morning"],
    availability: ["Monday", "Wednesday", "Friday"],
    looking_for: ["training partner", "competition"],
    occupation: "Firefighter",
    current_streak: 16,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "hype",
    response_speed: "fast",
    main_goal: "Dominate the next competition",
    chat_notes: "High energy. Immediately asks what your training looks like.",
  },
  {
    id: "demo0033-0000-0000-0000-000000000033",
    email: "demo.maya@flexmatches-demo.local",
    username: "maya_ab",
    full_name: "Maya Jenkins",
    bio: "Yoga and running are my reset buttons. Train for mental health as much as physical. Looking for good energy.",
    sports: ["Running", "Yoga"],
    fitness_level: "intermediate",
    age: 28,
    gender: "female",
    city: "Abington",
    gym_name: "Anytime Fitness - Horsham",
    lat: 40.1156, lng: -75.1180,
    preferred_times: ["morning"],
    availability: ["Monday", "Wednesday", "Saturday"],
    looking_for: ["running partner", "wellness partner"],
    occupation: "Therapist",
    current_streak: 7,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "friendly",
    response_speed: "medium",
    main_goal: "Improve mental clarity through movement",
    chat_notes: "Asks how training makes you feel, not just metrics.",
  },
  {
    id: "demo0034-0000-0000-0000-000000000034",
    email: "demo.lauren@flexmatches-demo.local",
    username: "lauren_cycle",
    full_name: "Lauren Mitchell",
    bio: "Indoor cycling and strength training. 3 mornings a week, rain or shine. Consistency is the goal.",
    sports: ["Cycling", "Gym"],
    fitness_level: "intermediate",
    age: 32,
    gender: "female",
    city: "Jenkintown",
    gym_name: "Jenkintown YMCA",
    lat: 40.0939, lng: -75.1340,
    preferred_times: ["morning"],
    availability: ["Tuesday", "Thursday", "Saturday"],
    looking_for: ["gym buddy", "accountability"],
    occupation: "Dental Hygienist",
    current_streak: 9,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(2),
    personality: "direct",
    response_speed: "slow",
    main_goal: "Get leaner, stay disciplined",
    chat_notes: "Brief messages. Focused on logistics.",
  },
  {
    id: "demo0035-0000-0000-0000-000000000035",
    email: "demo.kayla@flexmatches-demo.local",
    username: "kayla_glenside",
    full_name: "Kayla Thompson",
    bio: "Gym newbie who's serious about changing habits. Would really appreciate a knowledgeable partner 😊",
    sports: ["Gym", "Yoga"],
    fitness_level: "beginner",
    age: 26,
    gender: "female",
    city: "Glenside",
    gym_name: "Planet Fitness - Willow Grove",
    lat: 40.1021, lng: -75.1527,
    preferred_times: ["evening"],
    availability: ["Monday", "Wednesday", "Friday"],
    looking_for: ["gym buddy", "accountability"],
    occupation: "Administrative Assistant",
    current_streak: 2,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "friendly",
    response_speed: "fast",
    main_goal: "Lose weight, build routine",
    chat_notes: "Asks for guidance. Enthusiastic when encouraged.",
  },
  {
    id: "demo0036-0000-0000-0000-000000000036",
    email: "demo.destiny@flexmatches-demo.local",
    username: "destiny_bball",
    full_name: "Destiny Jackson",
    bio: "I run, I ball, I grind. Looking for someone who can keep up and make me better 🏃‍♀️🏀",
    sports: ["Basketball", "Running"],
    fitness_level: "intermediate",
    age: 30,
    gender: "female",
    city: "Warminster",
    gym_name: "LA Fitness - Warminster",
    lat: 40.1992, lng: -75.0874,
    preferred_times: ["evening"],
    availability: ["Tuesday", "Thursday", "Sunday"],
    looking_for: ["sports partner", "training partner"],
    occupation: "Retail Manager",
    current_streak: 6,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "hype",
    response_speed: "medium",
    main_goal: "Stay sharp, stay fast",
    chat_notes: "Competitive and enthusiastic. Asks about your athletic background.",
  },
  {
    id: "demo0037-0000-0000-0000-000000000037",
    email: "demo.chloe@flexmatches-demo.local",
    username: "chloe_swim",
    full_name: "Chloe Martin",
    bio: "Lap swimmer and very new to yoga. Prefer mornings before everything gets chaotic.",
    sports: ["Swimming", "Yoga"],
    fitness_level: "beginner",
    age: 23,
    gender: "female",
    city: "Willow Grove",
    gym_name: "Jenkintown YMCA",
    lat: 40.1419, lng: -75.1252,
    preferred_times: ["morning"],
    availability: ["Monday", "Wednesday"],
    looking_for: ["swim buddy", "wellness partner"],
    occupation: "Graduate Student",
    current_streak: 1,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(3),
    personality: "reserved",
    response_speed: "slow",
    main_goal: "Improve lap time, stay calm",
    chat_notes: "Short and a bit formal. Warms up slowly.",
  },
  {
    id: "demo0038-0000-0000-0000-000000000038",
    email: "demo.nadia@flexmatches-demo.local",
    username: "nadia_ultra",
    full_name: "Nadia Korostova",
    bio: "Ultrarunner and weekend trail guide. Logged 1,200 miles last year. Looking for someone who wants to push limits.",
    sports: ["Running", "Hiking"],
    fitness_level: "advanced",
    age: 37,
    gender: "female",
    city: "Ambler",
    gym_name: "Ambler Fitness Center",
    lat: 40.1548, lng: -75.2218,
    preferred_times: ["morning"],
    availability: ["Wednesday", "Saturday", "Sunday"],
    looking_for: ["running partner", "outdoor partner"],
    occupation: "Physical Therapist",
    current_streak: 22,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "direct",
    response_speed: "medium",
    main_goal: "100-mile finish this year",
    chat_notes: "Serious about running. Asks about your weekly mileage.",
  },
  {
    id: "demo0039-0000-0000-0000-000000000039",
    email: "demo.samantha@flexmatches-demo.local",
    username: "sam_fw",
    full_name: "Samantha Greene",
    bio: "Evening gym sessions and Saturday morning runs. Work-life balance is hard — the gym keeps it manageable.",
    sports: ["Gym", "Running"],
    fitness_level: "intermediate",
    age: 28,
    gender: "female",
    city: "Fort Washington",
    gym_name: "24 Hour Fitness - Fort Washington",
    lat: 40.1438, lng: -75.2022,
    preferred_times: ["evening"],
    availability: ["Monday", "Wednesday", "Saturday"],
    looking_for: ["gym buddy", "accountability"],
    occupation: "Product Manager",
    current_streak: 6,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "friendly",
    response_speed: "fast",
    main_goal: "Tone up, relieve stress",
    chat_notes: "Easy conversationalist. Confirms plans carefully.",
  },
  {
    id: "demo0040-0000-0000-0000-000000000040",
    email: "demo.keisha@flexmatches-demo.local",
    username: "keisha_nw",
    full_name: "Keisha Brown",
    bio: "Yoga and strength training. I believe in slow and steady. Looking for a calm, consistent training partner.",
    sports: ["Yoga", "Gym"],
    fitness_level: "intermediate",
    age: 33,
    gender: "female",
    city: "North Wales",
    gym_name: "Gold's Gym - North Wales",
    lat: 40.2103, lng: -75.2756,
    preferred_times: ["morning"],
    availability: ["Tuesday", "Thursday", "Sunday"],
    looking_for: ["wellness partner", "gym buddy"],
    occupation: "Occupational Therapist",
    current_streak: 8,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(2),
    personality: "friendly",
    response_speed: "medium",
    main_goal: "Mind-body wellness",
    chat_notes: "Warm and measured. Asks about how you balance training with life.",
  },

  // ─── OTHER/MIXED 1–10 (41–50) ──────────────────────────────────────────────

  {
    id: "demo0041-0000-0000-0000-000000000041",
    email: "demo.alexj@flexmatches-demo.local",
    username: "alexj_fit",
    full_name: "Alex Jordan",
    bio: "Gym and yoga to stay balanced. I train because I like how it makes me feel, not for aesthetics.",
    sports: ["Gym", "Yoga"],
    fitness_level: "intermediate",
    age: 27,
    gender: "other",
    city: "Willow Grove",
    gym_name: "Planet Fitness - Willow Grove",
    lat: 40.1429, lng: -75.1241,
    preferred_times: ["evening"],
    availability: ["Monday", "Wednesday", "Friday"],
    looking_for: ["gym buddy", "wellness partner"],
    occupation: "Librarian",
    current_streak: 5,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "friendly",
    response_speed: "fast",
    main_goal: "Feel strong, stay grounded",
    chat_notes: "Thoughtful tone. Mentions mindfulness and wellness.",
  },
  {
    id: "demo0042-0000-0000-0000-000000000042",
    email: "demo.casey@flexmatches-demo.local",
    username: "casey_h",
    full_name: "Casey Holt",
    bio: "Consistent runner, weekend hiker. Low drama, high effort. Looking for someone who just shows up.",
    sports: ["Running", "Hiking"],
    fitness_level: "intermediate",
    age: 29,
    gender: "other",
    city: "Horsham",
    gym_name: "Anytime Fitness - Horsham",
    lat: 40.1769, lng: -75.1489,
    preferred_times: ["morning"],
    availability: ["Wednesday", "Saturday"],
    looking_for: ["running partner", "outdoor partner"],
    occupation: "Copywriter",
    current_streak: 7,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "direct",
    response_speed: "medium",
    main_goal: "Build endurance, clear the head",
    chat_notes: "Minimal small talk. Asks about preferred routes.",
  },
  {
    id: "demo0043-0000-0000-0000-000000000043",
    email: "demo.jordanb@flexmatches-demo.local",
    username: "jordan_b43",
    full_name: "Jordan Blake",
    bio: "Campus baller and gym newbie. I want to learn and get better. Looking for someone patient and consistent 🙏",
    sports: ["Basketball", "Gym"],
    fitness_level: "beginner",
    age: 24,
    gender: "other",
    city: "Abington",
    gym_name: "Planet Fitness - Willow Grove",
    lat: 40.1161, lng: -75.1192,
    preferred_times: ["afternoon"],
    availability: ["Tuesday", "Thursday", "Saturday", "Sunday"],
    looking_for: ["gym buddy", "sports partner"],
    occupation: "Student",
    current_streak: 2,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "hype",
    response_speed: "fast",
    main_goal: "Get fit and improve on the court",
    chat_notes: "Enthusiastic. Asks about gym experience and programs.",
  },
  {
    id: "demo0044-0000-0000-0000-000000000044",
    email: "demo.quinn@flexmatches-demo.local",
    username: "quinn_j",
    full_name: "Quinn Lawson",
    bio: "Yoga twice a week, open water swimming in summer. Prefer low-impact, high-focus training.",
    sports: ["Yoga", "Swimming"],
    fitness_level: "intermediate",
    age: 31,
    gender: "other",
    city: "Jenkintown",
    gym_name: "Jenkintown YMCA",
    lat: 40.0957, lng: -75.1317,
    preferred_times: ["morning"],
    availability: ["Tuesday", "Saturday"],
    looking_for: ["wellness partner", "swim buddy"],
    occupation: "Nurse",
    current_streak: 4,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(3),
    personality: "reserved",
    response_speed: "slow",
    main_goal: "Recovery-focused fitness",
    chat_notes: "Deliberate replies. Prefers clear, scheduled plans.",
  },
  {
    id: "demo0045-0000-0000-0000-000000000045",
    email: "demo.riley@flexmatches-demo.local",
    username: "riley_g",
    full_name: "Riley Garcia",
    bio: "Gym 3 times a week and trying to add morning runs. Just want to be healthier and find my people.",
    sports: ["Gym", "Running"],
    fitness_level: "beginner",
    age: 26,
    gender: "other",
    city: "Glenside",
    gym_name: "Ambler Fitness Center",
    lat: 40.1034, lng: -75.1533,
    preferred_times: ["evening"],
    availability: ["Monday", "Thursday"],
    looking_for: ["gym buddy", "running partner"],
    occupation: "Food Service Worker",
    current_streak: 3,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(1),
    personality: "friendly",
    response_speed: "medium",
    main_goal: "Make exercise a habit",
    chat_notes: "Relatable and down-to-earth. Talks about everyday motivation.",
  },
  {
    id: "demo0046-0000-0000-0000-000000000046",
    email: "demo.avery@flexmatches-demo.local",
    username: "avery_cf",
    full_name: "Avery Collins",
    bio: "CrossFit 5 mornings a week. Results-driven. Not looking for a social club, looking for a training partner.",
    sports: ["CrossFit", "Gym"],
    fitness_level: "advanced",
    age: 33,
    gender: "other",
    city: "Warminster",
    gym_name: "CrossFit Horsham",
    lat: 40.1984, lng: -75.0903,
    preferred_times: ["morning"],
    availability: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    looking_for: ["training partner", "accountability"],
    occupation: "Personal Trainer",
    current_streak: 17,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "direct",
    response_speed: "fast",
    main_goal: "Top 10 at regional competition",
    chat_notes: "No fluff. Immediately talks training schedule.",
  },
  {
    id: "demo0047-0000-0000-0000-000000000047",
    email: "demo.morgank@flexmatches-demo.local",
    username: "morgan_k",
    full_name: "Morgan Kelly",
    bio: "I hike more than I should and do yoga to balance it out. Looking for chill, consistent outdoor company.",
    sports: ["Hiking", "Yoga"],
    fitness_level: "intermediate",
    age: 28,
    gender: "other",
    city: "Ambler",
    gym_name: "Ambler Fitness Center",
    lat: 40.1529, lng: -75.2253,
    preferred_times: ["morning"],
    availability: ["Saturday", "Sunday"],
    looking_for: ["outdoor partner", "wellness partner"],
    occupation: "Park Ranger",
    current_streak: 6,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(2),
    personality: "friendly",
    response_speed: "medium",
    main_goal: "Complete the Batona Trail loop",
    chat_notes: "Talks about specific trails and nature. Low-key energy.",
  },
  {
    id: "demo0048-0000-0000-0000-000000000048",
    email: "demo.river@flexmatches-demo.local",
    username: "river_fw",
    full_name: "River Stone",
    bio: "Morning runner and yoga beginner. Finding my rhythm and looking for company.",
    sports: ["Running", "Yoga"],
    fitness_level: "beginner",
    age: 25,
    gender: "other",
    city: "Fort Washington",
    gym_name: "Planet Fitness - Warminster",
    lat: 40.1442, lng: -75.2038,
    preferred_times: ["morning"],
    availability: ["Wednesday", "Saturday"],
    looking_for: ["running partner", "wellness partner"],
    occupation: "Barista",
    current_streak: 2,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(4),
    personality: "reserved",
    response_speed: "slow",
    main_goal: "Run a 5K without stopping",
    chat_notes: "Quiet until comfortable. Asks about your schedule.",
  },
  {
    id: "demo0049-0000-0000-0000-000000000049",
    email: "demo.kai@flexmatches-demo.local",
    username: "kai_nw",
    full_name: "Kai Nakamura",
    bio: "Pickup basketball and boxing are my thing. Looking for people who play hard and have fun 🏀🥊",
    sports: ["Basketball", "Boxing"],
    fitness_level: "intermediate",
    age: 30,
    gender: "other",
    city: "North Wales",
    gym_name: "Gold's Gym - North Wales",
    lat: 40.2107, lng: -75.2768,
    preferred_times: ["evening"],
    availability: ["Monday", "Wednesday", "Friday", "Sunday"],
    looking_for: ["sports partner", "training partner"],
    occupation: "Chef",
    current_streak: 8,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(0),
    personality: "hype",
    response_speed: "fast",
    main_goal: "Stay fast, stay sharp",
    chat_notes: "Energetic. Immediately suggests a time to play or spar.",
  },
  {
    id: "demo0050-0000-0000-0000-000000000050",
    email: "demo.sage@flexmatches-demo.local",
    username: "sage_hatboro",
    full_name: "Sage Patel",
    bio: "Yoga and hiking because balance matters. Looking for grounded, outdoorsy training partners in the area.",
    sports: ["Yoga", "Hiking"],
    fitness_level: "intermediate",
    age: 28,
    gender: "other",
    city: "Hatboro",
    gym_name: "Genesis Fitness - Hatboro",
    lat: 40.1729, lng: -75.1018,
    preferred_times: ["morning"],
    availability: ["Tuesday", "Saturday", "Sunday"],
    looking_for: ["wellness partner", "outdoor partner"],
    occupation: "Dietitian",
    current_streak: 5,
    avatar_url: null,
    onboarding_completed: true,
    last_active: ago(2),
    personality: "friendly",
    response_speed: "medium",
    main_goal: "Integrate movement with mindfulness",
    chat_notes: "Talks about how training connects to overall wellness.",
  },
];

// Fast lookup: is this a demo user?
export const DEMO_USER_IDS = new Set(DEMO_USERS.map((u) => u.id));

export function getDemoUser(id: string): DemoUser | undefined {
  return DEMO_USERS.find((u) => u.id === id);
}
